spring:
  application:
    name: uniTrade
  web:
    resources:
      static-locations: classpath:/static/
  data:
    mongodb:
      uri: "mongodb+srv://asibul279:uniTrade@unitrade.zjgqj.mongodb.net/?retryWrites=true&w=majority&appName=UniTrade"
      database: "UniTrade"
